CREATE TABLE CONVIDADOS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

INSERT INTO CONVIDADOS (ID, NOME) VALUES (1, 'Paulo Henrique');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (2, 'Conceição');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (3, 'Paulo Junior');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (4, 'Paola Santos');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (5, 'Juliane Ferraz');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (6, 'Mariana Monzani');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (7, 'Izaniele');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (8, 'Amanda Pilard');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (9, 'Gabriel (Amanda)');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (10, 'Vanessa Aquino');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (11, 'Lorena Aquino');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (12, 'Kristin Fayad');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (13, 'Rodrigo (kris)');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (14, 'Vitória (kris)');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (15, 'Samara Souza');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (16, 'Samira Falção');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (17, 'Marcel Bari');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (18, 'Cansu');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (19, 'Cansu Husband');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (20, 'Diana Gerbase');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (21, 'Diana namorado');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (22, 'Katia Lopes');
INSERT INTO CONVIDADOS (ID, NOME) VALUES (23, 'Filipe Oliveira');